version: '3.8'

services:
  favyt:
    build: .
    image: favyt:latest
    container_name: favyt
    restart: unless-stopped
    ports:
      - "8245:8245"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - TZ=Europe/Berlin
