services:
  favyt:
    image: akadawa/favyt:latest
    # build: .  # Uncomment this line if you want to build the image locally yourself
    container_name: favyt
    restart: unless-stopped
    ports:
      - "8245:8245"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - TZ=Europe/Berlin
